riscv-non-isa/riscv-toolchain-conventions

README.mkd

As far as I am aware the implementation of `-msave-restore` has not been documented anywhere. I'm unsure whether this or https://github.com/riscv/riscv-c-api-doc is the more appropriate place to document this.

Describe -msave-restore runtime library support

---

README.mkd

This is preparation for my upcoming proposals. Before proposals, we can clean this document to reflect latest statuses of GNU/LLVM toolchains and other external documents.
1. It updates links to external documents.
2. It reflects (not all but some of) current toolchain/ISA statuses:
- "G" is either "IMAFD" or "IMAFD_Zicsr_Zifencei" (depending on the target ISA)
- Because disassemblers assume availability of "Zicsr", "RV32/64GC" instead of "RV32/64 IMAFDC" would be better.
- Because "Zicsr" and "Zmmul" extensions are at least frozen, there's no need for "fine-grained information about a target" TODO.
- Both GNU and LLVM toolchains support parsing extension versions.

Update links and current statuses (batch 2022-02-20)

---

README.mkd

I'm preparing for new stuffs:
* Self-describing nature of RISC-V ELF files (`.riscv.attributes` section and related program header)
* ILP32E
* 'Q' extension (binary128 floating point support)
* Options already implemented by GNU/LLVM toolchain but not in this documentation
* New proposal for GNU/LLVM disassembler implementations.
... and this is another batch for consistency of the documentation (preparation before new stuffs).

Minor formatting and additions

---

README.mkd

This PR adds a commit on top of PR #17 that introduces `th` as the instruction prefix for T-Head vendor extensions.

Define prefix for T-Head vendor extensions

---

README.mkd

Similar to #19, this adds two additional T-Head vendor extensions (XTheadFmv and XTheadInt), which are documented here:
https://github.com/T-head-Semi/thead-extension-spec
Note that these extensions (as well as the already documented extensions) consist of instructions that are already implemented in existing cores (e.g. the E907).

Vendor extensions: Add two additional T-Head vendor extensions

---

README.mkd

SiFive published vector coprocessor interface spec, it included assembly mnemonic, instrucion encoding and C intrinsic interface.

Vendor extensions: Add SiFive vendor extensions: xsfvcp

---

README.mkd

A recent patch introduced the SiFive extensions at the wrong position. Let's fix that.
Signed-off-by: Christoph Müllner <christoph.muellner@vrull.eu>

Vendor extensions: Fix alphabetical order

---

README.mkd

This patch defines the Nuclei Instruction prefix `xl`, abbreviation of XinLai(Chinese pronunciation of Nuclei 芯来科技).

Vendor extensions: Add Nuclei vendor extensions

---

README.mkd

Support for all OpenHW CORE-V processors is planned to be
upstreamed to both GCC and Clang/LLVM
* README.mkd (List of vendor prefixes): Add CV for all OpenHW Group CORE-V cores. (List of vendor extensions) Add all eight CORE-V ISA extensions.
Signed-off-by: Jeremy Bennett <jeremy.bennett@embecosm.com>

Add vendor specific information for OpenHW Group CORE-V processors

---

README.mkd

Changes:
2021/08/16: Remove order constraint between single-letter and multi-letter, also add 2 more NOTE.
---
It's corresponding for https://github.com/riscv/riscv-toolchain-conventions/issues/11 ,

Relax the ISA string order checking for -march

---

README.mkd

This patch adds XTheadVector to the list of vendor extensions.

Vendor extensions: Add XTheadVector to list of vendor extensions

---

README.mkd

A hint that medlow might get deprecated in the future is a) useless, and b) misleading.
Let's drop that.
This came up as part of https://github.com/riscv-non-isa/riscv-toolchain-conventions/issues/42.

Remove hint for deprecating medlow

---

README.mkd

We have add few document into RISC-V psABI, so put link here to prevent we need to repeat that here.
Also add PIC mode into this doc.

Add code model link to psabi and add PIC model

---

README.mkd

In the last LLVM sync up meeting, we have dicussed the vendor CSR stuffs, and we realized that we have rule for vendor extenison name and assembly mnemonic, but no rule for vendor CSR naming scheme yet.
So it's would be great we have one before anyone start to upstream their own CSR definition.
The naming scheme basically follow the assembly mnemonic - use vendor prefix, the only difference is use underscore rather than dot, because it could be used in marco definition, but dot can't, that's an important character since that allow user to use marco before assmbler support, and eaiser to migrate to new version once assmbler support.

Add rule for vendor CSR naming scheme

---

README.mkd

Remove ordering from the list of issues to be considered. Its already stated that any order should be accepted.

Grammar fixes to target ISA section

---

README.mkd

We have those two option for a while, but not document in this repo yet, however we are intend to claify the scope of the option recently, so it's time to document down what we have agree among different community.

Add document for -mstrict-align and -mno-strict-align

---

README.mkd

Add two new option `-m[no-]scalar-strict-align` for alias of `-m[no-]-strict-align` and `-m[no-][vector]-strict-align` for vector misaligned access.

Add -m[no-][scalar|vector]-strict-align

---

src/toolchain-conventions.adoc

This patch defines the Andes instruction prefix `nds`.

Vendor extensions: Add Andes vendor extensions

---

src/toolchain-conventions.adoc

Hi, we'd like to reserve 'tt' as a vendor extension prefix, thanks

Vendor extensions: Add Tenstorrent vendor prefix

---

src/toolchain-conventions.adoc

Cheriot (https://cheriot.org/) is a RISC-V-based microcontroller platform that incorporates CHERI technology for capability-based security. It extends RISC-V with several new instructions (found in the ISA reference on cheriot.org). Some of these share names with the Zcheri extension currently under consideration, but do not use the same encodings, and thus should be in a vendor prefix.
The Cheriot LLVM toolchain is maintained in https://github.com/cherIoT-Platform/llvm-project It does not currently use a prefix on its custom instructions, but we would like to change that if we can assign a prefix.

Propose vendor mnemonic extension for CHERIoT

---

src/toolchain-conventions.adoc

This change reserves the vendor prefix "ri." for Rivos's custom extensions.

Introduce vendor prefix for Rivos custom extensions

---

src/toolchain-conventions.adoc

This patch defines the SpacemiT instruction prefix `smt`.

Vendor extensions: Add SpacemiT vendor prefix

---

src/toolchain-conventions.adoc

Defined a vendor prefix for Qualcomm Microcontroller Extensions.
Qualcomm extensions are public and defined at
https://github.com/quic/riscv-unified-db/releases
The list of extensions will be added in separate commit.
Support for these extensions in the LLVM toolchain is also in progress.
Change-Id: I59b4c7c7e01f44f27e0255a21a6f9650c70d75ee

Added Qualcomm vendor prefix

---

src/toolchain-conventions.adoc

Adding extensions for MIPS vendor:
1. xmipscmov
2. xmipslsp
3. xmipscbop
4. xmipsexectl
The official product page here:
https://mips.com/products/hardware/p8700/
Upstreaming of this in LLVM and binutils is in progress.

Add MIPS extensions

---

src/appendix.adoc
src/riscv-toolchain.adoc
src/toolchain-conventions.adoc

The list of vendor extensions provides an informational reference for the extensions supported by vendors. We discussed moving it to an appendix at the Toolchains SIG meeting held on 03/27/2025.

Moved list of vendor extensions to the appendix

---

src/toolchain-conventions.adoc

This is a subset work form https://github.com/riscv-non-isa/riscv-toolchain-conventions/pull/26.
Add RISC-V Profiles format only. The doc record in:
https://docs.google.com/document/d/1TZXRIgVfQHWQ6xrZflHXUCSav6xNmliojrW2bEsvPno/edit.

Add RISC-V Profiles format

---

src/toolchain-conventions.adoc

This moves the profiles section right after the target ISA section as both explain the behavior of the -march flag.
Further, the wording is a bit tweaked.
No changes on the feature level of the profile support.

profiles: Move and tweak the profiles section

---

src/appendix.adoc

This patch defines the T-Head vendor extensions (XTheadVdot), which is documented here:
https://github.com/T-head-Semi/thead-extension-spec

Vendor extensions: Add 'XTheadVdot' T-Head vendor extensions

---

src/toolchain-conventions.adoc

The vendor identifier for Andes was added to LLVM
https://github.com/llvm/llvm-project/pull/137748.

Add Andes vendor identifier

---

src/toolchain-conventions.adoc

Add documentation for the -march=unset option that allows ignoring previous -march options and deriving architecture from -mcpu.
The -march=unset option is particularly useful for build systems and toolchain configurations where architecture should always be derived from CPU specification rather than potentially conflicting -march options.

Document -march=unset option behavior and usage
